### ISSUE TITLE
emacs

### ISSUE THREAD

**Issue by kpurdon** [domeide/domeide.github.io#3]
This is the current dockerfile-mode for emacs: https://github.com/spotify/dockerfile-mode

**Comment by marsam** [comment]
I'd also like to add [dockerfile.el](https://github.com/emacs-pe/dockerfile.el)

**Comment by Silex** [comment]
For docker interaction there is also https://github.com/Silex/docker.el

**Comment by vdemeester** [comment]
Both projects are now on domeide.github.io, I guess this one could be closed.

/cc @l0rd @kpurdon
